export const REDUCER_KEY = 'swData';

export const FETCH_PAGINATED = `${REDUCER_KEY}/FETCH_PAGINATED`;
export const SET_PAGINATED = `${REDUCER_KEY}/SET_PAGINATED`;
export const SET_COUNT = `${REDUCER_KEY}/SET_COUNT`;
export const SET_NEXT_PAGE = `${REDUCER_KEY}/SET_NEXT_PAGE`;
export const CHANGE_RESOURCE_NAME = `${REDUCER_KEY}/CHANGE_RESOURCE_NAME`;
export const FETCH_SINGLE_ITEM = `${REDUCER_KEY}/FETCH_SINGLE_ITEM`;
export const SET_RESOURCE_NAME = `${REDUCER_KEY}/SET_RESOURCE_NAME`;
export const SET_SINGLE_ITEM = `${REDUCER_KEY}/SET_SINGLE_ITEM`;
export const CLEAR_SINGLE_ITEM = `${REDUCER_KEY}/CLEAR_SINGLE_ITEM`;
export const SEARCH = `${REDUCER_KEY}/SEARCH`;
export const SET_SEARCH_RESULTS = `${REDUCER_KEY}/SET_SEARCH_RESULTS`;
